---
title: Smart Material Theme
timezone: UTC
collections:
  articles:
    title: Articles
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: Slick Material Design theme for Jekyll powered by Material Design Lite.
baseurl: "/jekyll-smart-material"
url: http://ssokurenko.github.io
copyright: "&copy; 2015-2016 Smart Material Theme"
markdown: kramdown
material_theme: blue-deep_orange
google-analytics-ua: UA-84475574-1
